# Generated by Django 5.2 on 2025-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authantication', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KfWZXctnQZZmtkQiEMU9LNBtu6IAtGdq', editable=False, max_length=32, unique=True),
        ),
    ]
