# Generated by Django 5.2 on 2025-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authantication', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='W2GBPqjV2HSIvfR5NVdYkQPE41qobCTM', editable=False, max_length=32, unique=True),
        ),
    ]
